# ROOT ?= ../../../..
# TESTCASE ?= $(ROOT)/lmfrnet
#
# include $(TESTCASE)/.active_config.mk
#
# VLEN ?= 64
# LMUL ?= m1
#
# $(shell cp $(TESTCASE)/.active_config.mk ./active_config.mk)

include ../../active_config.mk

include ../common/common.mk
